### ISSUE TITLE
Bootstrap 4.x update

### ISSUE THREAD

**Issue by anyssa** [romuloctba/watermene#7]
Can I update to Bootstrap 4.x?

**Comment by romuloctba** [comment]
Ofc

**Comment by romuloctba** [comment]
Please feel free to improve the UI as you can, because the current version is pretty much a fork from Watermark.js original Demo.... So BS4 and new layout would be much appreciated... There is also the need of a clean up the code, so if you find anything you want to remove, do it (carefully hehe)


Thanks SO MUCH for this

**Comment by anyssa** [comment]
Finally did #8. New design, code cleanup, Bootstrap 4 and more!

**Comment by romuloctba** [comment]
It is awesome, Im doing some testing with a opacity control and will merge it

**Comment by romuloctba** [comment]
It gave new life to Watermene!!!

Its Merge

I need to add a opacity control in the UI
